// ─────────────────────────────────────────────────────────────────────────
// Account "Ritratto" composer.
//
// Builds the bottom-up traveller portrait from REAL data only:
//   - seek / avoid          → verbatim chips the user selected (quiz rawSignal)
//   - ownWords              → the user's free-text constraint, if any
//   - axes                  → the 5 real trait axes (EMA-aggregated)
//   - chosen                → destinations the user actually committed to
//   - revealed              → divergence between what they SAID (quiz) and what
//                             they CHOSE (pick) — the most interesting signal
//   - evolution             → how the dominant lean shifted over time (≥3 snaps)
//
// The interpretive layer (portrait text + paradox) is generated by Haiku and is
// hard-constrained to the facts above: it must never invent a destination,
// count, saved moment, note or evolution. A single fabricated fact destroys
// trust in the whole portrait, so facts are computed here and only handed to
// the model as input — never asked for.
// ─────────────────────────────────────────────────────────────────────────

import Anthropic from "@anthropic-ai/sdk";
import { storage } from "./storage";
import {
  emaAggregate, axisReadout, categorizeSignal, AXIS_NAMES, MAPPING_VERSION,
  type TraitVector, type Axis, type AxisReadout, type RawSignal,
} from "@shared/traits";
import { computeAccountInsights, continentOf } from "./account-insights";
import type { TraitSnapshot } from "@shared/schema";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export type PortraitConfidence = "nascent" | "forming" | "solid";

export interface PortraitChosen { name: string; date: string | null; }
export interface PortraitRevealed { saidPole: string; chosePole: string; theme: string; }
export interface PortraitEvolution {
  phrase: string;                                          // ready-to-render IT sentence
  points: Array<{ whenLabel: string; isNow: boolean }>;    // timeline ticks
}
export interface PortraitNarrative { portrait: string; paradox: string | null; }

export interface PortraitResponse {
  available: boolean;
  confidence: PortraitConfidence;
  tripCount: number;
  snapshotCount: number;
  seek: string[];
  avoid: string[];
  ownWords: string | null;
  axes: AxisReadout[];
  chosen: PortraitChosen[];
  counts: { destinations: number; days: number; continents: number };
  revealed: PortraitRevealed | null;
  evolution: PortraitEvolution | null;
  narrative: PortraitNarrative | null;
}

const MONTH_IT = ["gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic"];
function shortDate(iso: string | Date | null | undefined): string | null {
  if (!iso) return null;
  const d = iso instanceof Date ? iso : new Date(iso);
  if (isNaN(d.getTime())) return null;
  return `${MONTH_IT[d.getMonth()]} ${d.getFullYear()}`;
}

function monthsAgo(d: Date): number {
  return Math.max(0, Math.round((Date.now() - d.getTime()) / (30 * 24 * 3600 * 1000)));
}
function relativeWhenIT(d: Date): string {
  const m = monthsAgo(d);
  if (m >= 18) return "Più di un anno fa";
  if (m >= 10) return "Circa un anno fa";
  if (m >= 4) return "Qualche mese fa";
  return "Di recente";
}

// ── Revealed preference: what you SAID vs what you CHOSE ────────────────────
// Aggregates quiz-source vs pick-source vectors separately. The pick vector is
// blended with the destination the user actually committed to, so a gap between
// the two is a genuine "revealed preference" — the divergence the trait engine
// is explicitly designed to surface.
function computeRevealed(snapshots: TraitSnapshot[]): PortraitRevealed | null {
  const quiz = snapshots.filter(s => s.source === "quiz").map(s => s.traits as TraitVector);
  const pick = snapshots.filter(s => s.source === "pick").map(s => s.traits as TraitVector);
  if (quiz.length === 0 || pick.length === 0) return null;

  const q = emaAggregate(quiz);
  const p = emaAggregate(pick);

  let best: { axis: Axis; diff: number } | null = null;
  for (const axis of Object.keys(q) as Axis[]) {
    const flips = (q[axis] - 0.5) * (p[axis] - 0.5) < 0; // opposite sides of neutral
    const diff = Math.abs(p[axis] - q[axis]);
    if (flips && diff > 0.12 && (!best || diff > best.diff)) best = { axis, diff };
  }
  if (!best) return null;

  const labels = AXIS_NAMES[best.axis];
  const saidPole = q[best.axis] < 0.5 ? labels.it.left : labels.it.right;
  const chosePole = p[best.axis] < 0.5 ? labels.it.left : labels.it.right;
  return { saidPole, chosePole, theme: `${labels.it.left} ↔ ${labels.it.right}` };
}

// ── Evolution: how the dominant lean shifted over time ──────────────────────
function computeEvolution(snapshots: TraitSnapshot[]): PortraitEvolution | null {
  const valid = snapshots.filter(s => s.mappingVersion === MAPPING_VERSION);
  if (valid.length < 3) return null;

  const first = valid[0].traits as TraitVector;
  const current = emaAggregate(valid.map(s => s.traits as TraitVector));

  // Axis that moved the most.
  let best: { axis: Axis; delta: number } | null = null;
  for (const axis of Object.keys(current) as Axis[]) {
    const delta = current[axis] - first[axis];
    if (!best || Math.abs(delta) > Math.abs(best.delta)) best = { axis, delta };
  }
  if (!best || Math.abs(best.delta) < 0.12) return null;

  const labels = AXIS_NAMES[best.axis];
  const firstDate = valid[0].createdAt instanceof Date ? valid[0].createdAt : new Date(valid[0].createdAt as any);
  const when = relativeWhenIT(firstDate);

  const flips = (first[best.axis] - 0.5) * (current[best.axis] - 0.5) < 0;
  const oldPole = first[best.axis] < 0.5 ? labels.it.left : labels.it.right;
  const newPole = current[best.axis] < 0.5 ? labels.it.left : labels.it.right;
  const phrase = flips
    ? `${when} cercavi ${oldPole}, oggi ${newPole}.`
    : `Stai diventando sempre più ${newPole}.`;

  // Timeline ticks: first, optional middle, now.
  const points: PortraitEvolution["points"] = [];
  const firstYear = !isNaN(firstDate.getTime()) ? String(firstDate.getFullYear()) : "inizio";
  points.push({ whenLabel: firstYear, isNow: false });
  if (valid.length >= 5) {
    const mid = valid[Math.floor(valid.length / 2)];
    const md = mid.createdAt instanceof Date ? mid.createdAt : new Date(mid.createdAt as any);
    if (!isNaN(md.getTime())) points.push({ whenLabel: String(md.getFullYear()), isNow: false });
  }
  points.push({ whenLabel: "oggi", isNow: true });

  return { phrase, points };
}

// ── Haiku narrative (interpretive layer, fact-locked) ───────────────────────
interface NarrativeCacheEntry { key: string; value: PortraitNarrative; }
const narrativeCache = new Map<number, NarrativeCacheEntry>();

function buildFactsBlock(p: PortraitResponse): string {
  const lines: string[] = [];

  const strongAxes = p.axes.filter(a => a.magnitude !== "neutro");
  if (strongAxes.length) {
    lines.push("Assi psicologici (dominante per asse):");
    for (const a of strongAxes) lines.push(`- ${a.pole} (${a.magnitude})`);
  }
  if (p.seek.length) lines.push(`Ha scelto (cosa cerca): ${p.seek.join(", ")}.`);
  if (p.avoid.length) lines.push(`Ha indicato di voler evitare: ${p.avoid.join(", ")}.`);
  if (p.ownWords) lines.push(`Parole sue (vincolo libero): "${p.ownWords}".`);
  if (p.chosen.length) lines.push(`Destinazioni realmente scelte: ${p.chosen.map(c => c.name).join("; ")}.`);
  lines.push(`Numeri reali: ${p.counts.destinations} viaggi, ${p.counts.days} giorni, ${p.counts.continents} continenti.`);
  if (p.revealed) lines.push(`Scarto rivelatore: a parole tende a "${p.revealed.saidPole}", ma scegliendo va verso "${p.revealed.chosePole}".`);
  if (p.evolution) lines.push(`Evoluzione nel tempo: ${p.evolution.phrase}`);

  return lines.join("\n");
}

async function generateNarrative(userId: number, p: PortraitResponse): Promise<PortraitNarrative | null> {
  const key = `${p.snapshotCount}::${p.seek.join(",")}::${p.avoid.join(",")}::${p.chosen.length}::${p.revealed ? 1 : 0}`;
  const cached = narrativeCache.get(userId);
  if (cached && cached.key === key) return cached.value;

  if (!process.env.ANTHROPIC_API_KEY) return null;
  const facts = buildFactsBlock(p);
  if (!facts.trim()) return null;

  try {
    const message = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 480,
      system:
        "Sei l'assistente di MindRoute. Scrivi il \"ritratto\" di viaggio di una persona usando ESCLUSIVAMENTE i fatti forniti. " +
        "NON inventare destinazioni, conteggi, salvataggi, note o evoluzioni temporali non presenti nei dati. " +
        "Se un dato manca, ometti quella frase. Meglio un ritratto breve e vero che uno ricco e falso. " +
        "Testo in italiano, seconda persona singolare, caldo e specifico. Niente aggettivi vuoti (unico, speciale, perfetto), niente emoji, niente virgolette. " +
        "Rispondi SOLO con un oggetto JSON valido con due campi: " +
        "\"portrait\" (2-3 frasi che sintetizzano chi è come viaggiatore, basate sui fatti) e " +
        "\"paradox\" (UNA frase evocativa su una tensione reale tra i fatti, es. comfort + offbeat; null se i fatti non ne suggeriscono una).",
      messages: [{
        role: "user",
        content: `Fatti reali su questa persona:\n${facts}\n\nGenera il JSON {"portrait": "...", "paradox": "..."|null}.`,
      }],
    });

    const block = message.content[0];
    if (block.type !== "text") return null;
    const raw = block.text.trim();
    const jsonStr = raw.startsWith("{") ? raw : raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1);
    const parsed = JSON.parse(jsonStr) as { portrait?: unknown; paradox?: unknown };
    const portrait = typeof parsed.portrait === "string" ? parsed.portrait.trim() : "";
    if (!portrait) return null;
    const rawParadox = typeof parsed.paradox === "string" ? parsed.paradox.trim() : "";
    const paradox = rawParadox && !/^(null|none|nessuno|-)$/i.test(rawParadox) ? rawParadox : null;

    const value: PortraitNarrative = { portrait, paradox };
    narrativeCache.set(userId, { key, value });
    return value;
  } catch (e) {
    console.warn("[portrait] Haiku narrative failed:", e);
    return null;
  }
}

// ── Public entry ────────────────────────────────────────────────────────────
export async function buildPortrait(userId: number): Promise<PortraitResponse> {
  const snapshots = await storage.getTraitSnapshots(userId); // asc by createdAt
  const valid = snapshots.filter(s => s.mappingVersion === MAPPING_VERSION);
  const validVectors = valid.map(s => s.traits as TraitVector);

  const trips = await storage.getUserItineraries(userId);
  const { stats } = computeAccountInsights(trips);

  // Verbatim seek/avoid + own words: only from a genuine quiz snapshot (synthetic
  // "Genera dal profilo" snapshots carry null rawSignal and are skipped).
  let seek: string[] = [];
  let avoid: string[] = [];
  let ownWords: string | null = null;
  for (let i = valid.length - 1; i >= 0; i--) {
    const s = valid[i];
    if (s.source !== "quiz" || !s.rawSignal) continue;
    const rs = s.rawSignal as RawSignal;
    const cat = categorizeSignal(rs);
    if (cat.seek.length || cat.avoid.length) {
      seek = cat.seek;
      avoid = cat.avoid;
      const c = (rs.constraints ?? "").trim();
      ownWords = c.length >= 8 ? c : null; // skip trivial/empty constraints
      break;
    }
  }

  const axes = validVectors.length ? axisReadout(emaAggregate(validVectors)) : [];

  const chosen: PortraitChosen[] = trips.slice(0, 6).map(t => ({
    name: (t.destinationName ?? "Itinerario").split(",")[0].trim(),
    date: shortDate(t.createdAt),
  }));

  const continents = new Set<string>();
  for (const t of trips) {
    const c = continentOf(t);
    if (c) continents.add(c);
  }
  const counts = {
    destinations: stats.destinationsExplored,
    days: stats.daysImagined,
    continents: continents.size,
  };

  const revealed = computeRevealed(valid);
  const evolution = computeEvolution(valid);

  const snapshotCount = valid.length;
  const confidence: PortraitConfidence =
    snapshotCount >= 4 ? "solid" : snapshotCount >= 2 ? "forming" : "nascent";

  const available = validVectors.length >= 1 || seek.length > 0 || avoid.length > 0;

  const response: PortraitResponse = {
    available,
    confidence,
    tripCount: trips.length,
    snapshotCount,
    seek,
    avoid,
    ownWords,
    axes,
    chosen,
    counts,
    revealed,
    evolution,
    narrative: null,
  };

  if (available) response.narrative = await generateNarrative(userId, response);
  return response;
}
