// ─────────────────────────────────────────────────────────────────────────
// Trait headline — short sentence (in the user's UI language) describing the
// aggregated profile, generated by Haiku. Cached in-memory keyed on (userId,
// snapshot count + patterns + lang): if none of those changed, the headline
// can't have changed, so we skip the API call.
//
// The pure-client fallback ("Sei offbeat, intimo.") in MyAccount.tsx still
// works without this — Haiku adds nuance, not function.
// ─────────────────────────────────────────────────────────────────────────

import Anthropic from "@anthropic-ai/sdk";
import { AXIS_NAMES, type TraitVector, type Axis } from "@shared/traits";
import type { PatternSignals } from "./account-insights";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

interface CacheEntry {
  headline: string;
  // Cache key incorpora snapshotCount + un hash dei pattern (continent+avg).
  // Se uno dei due cambia, la headline va rigenerata.
  key: string;
}
const cache = new Map<number, CacheEntry>();

function patternKey(p?: PatternSignals | null): string {
  if (!p) return "none";
  return `${p.topContinent ?? ""}|${p.avgDays ?? ""}|${p.tripCount}`;
}

function describeVector(vector: TraitVector, lang: "en" | "it"): string {
  const lines: string[] = [];
  for (const axis of Object.keys(vector) as Axis[]) {
    const v = vector[axis];
    if (v >= 0.40 && v <= 0.60) continue;
    const names = AXIS_NAMES[axis];
    const labels = lang === "it" ? names.it : names;
    const pole = v < 0.5 ? labels.left : labels.right;
    const dist = Math.abs(v - 0.5);
    const mag = dist > 0.30 ? "forte" : dist > 0.18 ? "chiaro" : "lieve";
    lines.push(`- ${axis}: ${mag} ${pole}`);
  }
  return lines.join("\n");
}

function describePatterns(p: PatternSignals, lang: "en" | "it"): string {
  const it = lang === "it";
  const lines: string[] = [];
  if (p.topContinent && p.topContinentRatio !== null && p.topContinentRatio >= 0.4) {
    const pct = Math.round(p.topContinentRatio * 100);
    lines.push(it
      ? `- continente preferito: ${p.topContinent} (${pct}% dei viaggi)`
      : `- favourite continent: ${p.topContinent} (${pct}% of trips)`);
  }
  if (p.avgDays !== null) {
    const avg = p.avgDays.toFixed(1);
    if (p.shortTripBias) lines.push(it ? `- preferisci viaggi brevi (media ${avg} giorni)` : `- prefers short trips (avg ${avg} days)`);
    else if (p.longTripBias) lines.push(it ? `- preferisci viaggi lunghi (media ${avg} giorni)` : `- prefers long trips (avg ${avg} days)`);
    else lines.push(it ? `- durata media: ${avg} giorni` : `- average duration: ${avg} days`);
  }
  return lines.join("\n");
}

export async function getTraitHeadline(
  userId: number,
  vector: TraitVector,
  snapshotCount: number,
  patterns?: PatternSignals | null,
  lang: "en" | "it" = "it",
): Promise<string | null> {
  // Cache hit — la chiave incorpora snapshotCount + pattern key + lingua,
  // così cambia quando il profilo, i pattern o la lingua cambiano.
  const key = `${lang}::${snapshotCount}::${patternKey(patterns)}`;
  const cached = cache.get(userId);
  if (cached && cached.key === key) return cached.headline;

  if (!process.env.ANTHROPIC_API_KEY) return null;
  const description = describeVector(vector, lang);
  if (!description) return null; // all axes neutral — no signal to headline

  const patternBlock = patterns ? describePatterns(patterns, lang) : "";

  try {
    const message = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 140,
      messages: [{
        role: "user",
        content: lang === "it"
          ? `Sei l'assistente di MindRoute, una piattaforma di viaggio psicologica. Genera UNA SOLA frase italiana di 10-18 parole che descriva il profilo di viaggio di questa persona, COMBINANDO tratti psicologici E pattern di comportamento (continente preferito, durata media). Esempio di tono: "Sei un esploratore contemplativo che torna in Europa per viaggi brevi e intensi." Usa la seconda persona singolare. NIENTE aggettivi vuoti come "unico", "speciale", "perfetto". Niente emoji. Niente virgolette. Solo la frase, nient'altro.

Profilo psicologico (aggregato su ${snapshotCount} viaggi):
${description}
${patternBlock ? `\nPattern dai viaggi generati:\n${patternBlock}` : ""}

Una sola frase, italiana, 10-18 parole.`
          : `You are the MindRoute assistant, a psychological travel platform. Generate ONE ENGLISH sentence of 10-18 words describing this person's travel profile, COMBINING psychological traits AND behavioural patterns (favourite continent, average duration). Tone example: "You're a contemplative explorer who returns to Europe for short, intense trips." Use second person singular. NO empty adjectives like "unique", "special", "perfect". No emoji. No quotation marks. Only the sentence, nothing else.

Psychological profile (aggregated over ${snapshotCount} trips):
${description}
${patternBlock ? `\nPatterns from generated trips:\n${patternBlock}` : ""}

One sentence, English, 10-18 words.`,
      }],
    });

    const block = message.content[0];
    if (block.type !== "text") return null;
    const headline = block.text.trim().replace(/^["']|["']$/g, "").replace(/\s+/g, " ");
    if (!headline || headline.length > 240) return null;

    cache.set(userId, { headline, key });
    return headline;
  } catch (e) {
    console.warn("[trait-headline] Haiku call failed:", e);
    return null;
  }
}
