// ─────────────────────────────────────────────────────────────────────────
// Trait headline — short Italian sentence describing the user's aggregated
// profile, generated by Haiku. Cached in-memory keyed on (userId, snapshot
// count): if snapshot count hasn't grown, the headline can't have changed,
// so we skip the API call.
//
// The pure-client fallback ("Sei offbeat, intimo.") in MyAccount.tsx still
// works without this — Haiku adds nuance, not function.
// ─────────────────────────────────────────────────────────────────────────

import Anthropic from "@anthropic-ai/sdk";
import { AXIS_NAMES, type TraitVector, type Axis } from "@shared/traits";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

interface CacheEntry {
  headline: string;
  snapshotCount: number;
}
const cache = new Map<number, CacheEntry>();

function describeVector(vector: TraitVector): string {
  const lines: string[] = [];
  for (const axis of Object.keys(vector) as Axis[]) {
    const v = vector[axis];
    if (v >= 0.40 && v <= 0.60) continue;
    const labels = AXIS_NAMES[axis];
    const pole = v < 0.5 ? labels.it.left : labels.it.right;
    const dist = Math.abs(v - 0.5);
    const mag = dist > 0.30 ? "forte" : dist > 0.18 ? "chiaro" : "lieve";
    lines.push(`- ${axis}: ${mag} ${pole}`);
  }
  return lines.join("\n");
}

export async function getTraitHeadline(
  userId: number,
  vector: TraitVector,
  snapshotCount: number,
): Promise<string | null> {
  // Cache hit — snapshot count unchanged means no new signal, headline can be reused.
  const cached = cache.get(userId);
  if (cached && cached.snapshotCount === snapshotCount) return cached.headline;

  if (!process.env.ANTHROPIC_API_KEY) return null;
  const description = describeVector(vector);
  if (!description) return null; // all axes neutral — no signal to headline

  try {
    const message = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 120,
      messages: [{
        role: "user",
        content: `Sei l'assistente di MindRoute, una piattaforma di viaggio psicologica. Genera UNA SOLA frase italiana di 8-14 parole che descriva il profilo di viaggio di questa persona. Usa la seconda persona singolare ("Cerchi...", "Sei...", "Ti muovi..."). NIENTE aggettivi vuoti come "unico", "speciale", "perfetto". Niente emoji. Niente virgolette. Solo la frase, nient'altro.

Profilo aggregato su ${snapshotCount} viaggi:
${description}

Una sola frase, italiana, 8-14 parole.`,
      }],
    });

    const block = message.content[0];
    if (block.type !== "text") return null;
    const headline = block.text.trim().replace(/^["']|["']$/g, "").replace(/\s+/g, " ");
    if (!headline || headline.length > 200) return null;

    cache.set(userId, { headline, snapshotCount });
    return headline;
  } catch (e) {
    console.warn("[trait-headline] Haiku call failed:", e);
    return null;
  }
}
